# Production server deployment settings

# DIA-NN settings
threads: 64
diann_docker_image: "diann:2.3.1"

# File conversion
raw_converter_docker: "thermorawfileparser:linux"
raw_converter_binary: ""  # Not used on server (Docker only)
use_msconvert: "true"
msconvert_docker: "chambm/pwiz-skyline-i-agree-to-the-vendor-licenses"

# QC and staging
prolfquapp_version: "2.0.7"
app_runner: "fgcz_app_runner"
